// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Rjr8qOtlnqA8_EBkr3-yBXog6ZPNcYk',
    appId: '1:395464795202:web:7dcdcc3127278f214d79db',
    messagingSenderId: '395464795202',
    projectId: 'instagram-clone-f55a0',
    authDomain: 'instagram-clone-f55a0.firebaseapp.com',
    storageBucket: 'instagram-clone-f55a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKy5oWVYH-gdcA0lns0OlnkSeW9Q9i1XQ',
    appId: '1:395464795202:android:c3ecb8c08b5a069c4d79db',
    messagingSenderId: '395464795202',
    projectId: 'instagram-clone-f55a0',
    storageBucket: 'instagram-clone-f55a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-js--E3ZxNf4NhjzpdZm2lx-MzIGlP8',
    appId: '1:395464795202:ios:52455d1d2d507c394d79db',
    messagingSenderId: '395464795202',
    projectId: 'instagram-clone-f55a0',
    storageBucket: 'instagram-clone-f55a0.appspot.com',
    iosClientId: '395464795202-qgf89n79psarqamq9l4rhfe1efnbvkjv.apps.googleusercontent.com',
    iosBundleId: 'com.gmmyung.instagramclone',
  );
}
